apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-insights

resources:
  - namespace.yaml
  - secrets.yaml
  - milvus.yaml
  - ai-insights.yaml

commonLabels:
  app.kubernetes.io/name: studio-pilot-ai
  app.kubernetes.io/part-of: studio-pilot
